### ISSUE TITLE
issues mc server

### ISSUE THREAD

**Issue by rekoi74** [rekoi74/MC#1]
Ok... deci,in opinia mea,tickrate-ul nu are sens.Nu am vazut pe vreun server tickrate vreodata.Ocupa prea mult spatiu IMO.
![image](https://user-images.githubusercontent.com/34631606/34083419-604495f2-e379-11e7-8723-c5b5b32e7516.png)
Problema 2 : kit VIP,VIP+ sunt inexistente.
![image](https://user-images.githubusercontent.com/34631606/34083430-760314c2-e379-11e7-84f8-a6c5eac37f30.png)
Problema 3 : nu pot apasa pe RandomTP si pe Like FlipSideMC
Problema 4 : ce s-a intamplat cu FlipsideMC de pe playerlist?

![image](https://user-images.githubusercontent.com/34631606/34083481-22212794-e37a-11e7-9761-1e026e7538f9.png)

Problema 5 : simt ca liniutele alea de legare sunt destul de useless...
![image](https://user-images.githubusercontent.com/34631606/34083490-40886b48-e37a-11e7-9ac0-a9bc745cd3e3.png)

Problema 6 : aia de la shop au folosit culori diferite si fonturi la nu se vinde signs

cel normal : 

![image](https://user-images.githubusercontent.com/34631606/34083497-618bf968-e37a-11e7-83ee-1853acacef73.png) (la brewing shit)

cele modificate : 

![image](https://user-images.githubusercontent.com/34631606/34083499-68ddbfc6-e37a-11e7-937b-715d7a529123.png) (la lana,dyes si culori)

ala e un gri chior ca naiba

![image](https://user-images.githubusercontent.com/34631606/34083514-a711cbc0-e37a-11e7-99c5-b2383143d6e8.png) (la etajul 2,la anvil,la unelte)

nu inteleg de ce e atata varietate...?

meh,shop-ul are mult remaking in general sooo....

Problema 8 : Numele?

![image](https://user-images.githubusercontent.com/34631606/34083532-e78c63ea-e37a-11e7-8cb5-027b8d87c632.png) (ma rog,radu le-a facut pe astea ca satana are spelling 10/10 👌 )

![image](https://user-images.githubusercontent.com/34631606/34083534-eca06ed0-e37a-11e7-98ce-19d34bd936c5.png)

Culori?

![image](https://user-images.githubusercontent.com/34631606/34083538-0a909e88-e37b-11e7-83b4-56bf2a36070b.png)

Si de ce e blaze cu bold?

Problema 9 : Ce e cu chest-ul asta?

![image](https://user-images.githubusercontent.com/34631606/34083565-ad8450c6-e37b-11e7-80bf-d2b91e59ab62.png)

Problema 10 : un space extra?

![image](https://user-images.githubusercontent.com/34631606/34083630-490c5372-e37c-11e7-9476-946ca4c6e8ae.png)

Problema 11 : traducere la /gunoi

![image](https://user-images.githubusercontent.com/34631606/34083647-799c712a-e37c-11e7-9433-a87c73ca7bdd.png)

Problema 12 : traducere la /tv

![image](https://user-images.githubusercontent.com/34631606/34083654-8811a428-e37c-11e7-9817-43b317c72f89.png)

PROBLEMA MARE 1 : COMBINATIE LA SHOP 

![image](https://user-images.githubusercontent.com/34631606/34083663-a59f5710-e37c-11e7-9ca0-6f1e23ad0ba9.png)

PROBLEMA MARE 2 : COMBINATIE LA SHOP

![image](https://user-images.githubusercontent.com/34631606/34083706-9758e954-e37d-11e7-95e5-b970be67e165.png) (asta e prea op,serios acuma radu?)

Nu am mai putut gasi nimic.

Sugestii : in opinia mea,jucatorii au nevoie de o comanda de enderchest ceva,minus aia cu sa vezi enderchest-urile la ceilalti jucatori 

Un plugin cu job-uri cu nivel,ca sa dea mai multi bani

Sa pui ceva fel de border la spawn (idk,just that looks so ugly that you can go out of spawn by a single jump)

**Comment by KoocieBoi** [comment]
4. [x] 4. *_E de la tine_*
